# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Novus < Formula
  desc "A local HTTPS proxy for a delightful developer experience."
  homepage "https://github.com/jozefcipa/novus"
  version "0.0.7"
  license "MIT"
  depends_on :macos

  on_intel do
    url "https://github.com/jozefcipa/novus/releases/download/v0.0.7/novus_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
    sha256 "5aec9eff3667f67b6c42706d738949e2e68759ade5f44ace594e9426ba28ada7"

    def install
      bin.install "novus"
      prefix.install Dir["assets/"]
    end
  end
  on_arm do
    url "https://github.com/jozefcipa/novus/releases/download/v0.0.7/novus_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
    sha256 "828c6603c436dd67cfa0b24c014ad7f58b01a30032f5307006a22f855a472bb8"

    def install
      bin.install "novus"
      prefix.install Dir["assets/"]
    end
  end
end
